account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^logout-then-login/$', auth_views.logout_then_login, name='logout_then_login'),
    url(r'^password-change/$', auth_views.password_change, name='password_change'),
    url(r'^password-change/done/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^register/$', views.register, name='register'),
    url(r'^password-reset/$',auth_views.password_reset,name='password_reset'),
    url(r'^password-reset/done/$',auth_views.password_reset_done,name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',auth_views.password_reset_confirm,name='password_reset_confirm'),
    url(r'^password-reset/complete/$',auth_views.password_reset_complete,name='password_reset_complete'),


]

bagghali/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .views import redirect_root

urlpatterns = [
    url(r'^$', redirect_root),
    url(r'^account/', include('account.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^shop/', include('shop.urls', namespace='shop')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    url(r'^storage/$', views.storage, name='storage'),
    url(r'^statistic/$', views.statistic, name='statistic'),
    url(r'^product_delete/(?P<id>\d+)/$', views.product_delete, name='product_delete'),
    url(r'^product_edit/(?P<id>\d+)/$', views.product_edit, name='product_edit'),
    url(r'^transaction_delete/(?P<id>\d+)/$', views.transaction_delete, name='transaction_delete'),
    url(r'^transaction_accept/(?P<id>\d+)/$', views.transaction_accept, name='transaction_accept'),
    url(r'^transaction_edit/(?P<id>\d+)/$', views.transaction_edit, name='transaction_edit'),
]

account/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from django.contrib.auth.models import User


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('گذر واژه ها یکسان نیست')
        return cd['password2']

account/views.py
from django.shortcuts import render
from .forms import UserRegistrationForm
from django.contrib.auth.decorators import login_required
from shop.models import Product, Transaction
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from django.http import HttpResponse, HttpResponseRedirect



def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
        return render(request,
                      'account/register_done.html',
                      {'new_user': new_user})
    else :
        user_form = UserRegistrationForm()
    return render(request,
                  'account/register.html',
                  {'user_form': user_form})


@login_required
def dashboard(request):
    transactions = Transaction.undone.all()
    trans_paginator = Paginator(transactions,5)
    trans_page = request.GET.get('trans_page')

    products = Product.objects.all()[:10]
#   product_paginator = Paginator(products, 8)
#   product_page = request.GET.get('product_page')
    try:
        transactions = trans_paginator.page(trans_page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        transactions = trans_paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            # If the request is AJAX and the page is out of range
            # return an empty page
            return HttpResponse('')
        # If page is out of range deliver last page of results
            transactions = trans_paginator.page(trans_paginator.num_pages)
    if request.is_ajax():
        return render(request,
                      'account/trans_ajax.html',
                      {'section': 'dashboard',
                       'products': products,
                       'transactions':transactions})
    return render(request,
                  'account/dashboard.html',
                  {'section': 'dashboard',
                   'products': products ,
                   'transactions': transactions})

account/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static "css/base.css" %}" rel="stylesheet">
    </head>
    <body>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">
                        <a href="#" class="close">✖</a>
                        {{ message|safe }}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        <div id="header">
                {% if request.user.is_authenticated %}
                    <span class="user">
                        <a href="{% url "logout" %}" class="log-out">خروج</a>
                    </span>
                {% else %}
                {% endif %}
            {% if request.user.is_authenticated %}
                <ul class="menu">
                    <li class="home" {% if section == "dashboard" %}id="selected"{% endif %}><a
                        href="{% url "dashboard" %}">خانه</a>
                    </li>
                    <li class="head-stor" {% if section == "storage" %}id="selected"{% endif %}>
                        <a href="{% url "shop:storage" %}">انبار </a>
                    </li>
                    <li class="head-stat" {% if section == "statistic" %}id="selected"{% endif %}><a
                        href="{% url "shop:statistic" %}">آمار</a>
                    </li>
                </ul>
                <span class="total-stat">فروش کل : 125.252.215</span>
            {% endif %}
        </div>

        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
        <script src=" http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js "></script>
        <script>
        var csrftoken = $.cookie('csrftoken');
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
            $(document).ready(function(){
                {% block domready %}
                {% endblock %}
            });
        </script>
    </body>